//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peanut")]
        public string DefaultUserName {
            get {
                return ((string)(this["DefaultUserName"]));
            }
            set {
                this["DefaultUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MARIA")]
        public string DefaultChatbotName {
            get {
                return ((string)(this["DefaultChatbotName"]));
            }
            set {
                this["DefaultChatbotName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Because I\'m awesome!")]
        public string DefaultChatbotResponse {
            get {
                return ((string)(this["DefaultChatbotResponse"]));
            }
            set {
                this["DefaultChatbotResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Diagnostic")]
        public global::Galatea.Diagnostics.DebuggerLogLevel DebuggerLogLevel {
            get {
                return ((global::Galatea.Diagnostics.DebuggerLogLevel)(this["DebuggerLogLevel"]));
            }
            set {
                this["DebuggerLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message")]
        public global::Galatea.Diagnostics.DebuggerLogLevel DebuggerAlertLevel {
            get {
                return ((global::Galatea.Diagnostics.DebuggerLogLevel)(this["DebuggerAlertLevel"]));
            }
            set {
                this["DebuggerAlertLevel"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Data\\SerializedData.dat")]
        public string DataAccessManagerConnectionString {
            get {
                return ((string)(this["DataAccessManagerConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public short ColorTemplateHybridResultThreshold {
            get {
                return ((short)(this["ColorTemplateHybridResultThreshold"]));
            }
            set {
                this["ColorTemplateHybridResultThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          <ImagingSettings xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance" +
            "\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n            <Timeout>2000</Time" +
            "out>\r\n            <SuppressTimeout>true</SuppressTimeout>\r\n            <DebugRec" +
            "ognitionSaveImages>true</DebugRecognitionSaveImages>\r\n            <ColorStatsSet" +
            "tings>\r\n              <StatisticalAnalysisTypes>Mean</StatisticalAnalysisTypes>\r" +
            "\n            </ColorStatsSettings>\r\n            <MonochromeBlobFilterSettings>\r\n" +
            "              <ContrastCorrectionFactor>-64</ContrastCorrectionFactor>\r\n        " +
            "      <AdaptiveSmoothingFactor>0.25</AdaptiveSmoothingFactor>\r\n              <Fr" +
            "ameWidth>10</FrameWidth>\r\n            </MonochromeBlobFilterSettings>\r\n         " +
            "   <BlobPointSettings>\r\n              <LineSegmentThreshold>18</LineSegmentThres" +
            "hold>\r\n              <LineAngleThreshold>9</LineAngleThreshold>\r\n              <" +
            "CurveAngleThreshold>27</CurveAngleThreshold>\r\n            </BlobPointSettings>\r\n" +
            "            <TemplateRecognitionSettings>\r\n              <ColorBrightnessThresho" +
            "ld>6</ColorBrightnessThreshold>\r\n              <ColorSaturationThreshold>5</Colo" +
            "rSaturationThreshold>\r\n              <ShapeOblongThreshold>1.75</ShapeOblongThre" +
            "shold>\r\n              <ShapeOblongRecognitionLevel>2</ShapeOblongRecognitionLeve" +
            "l>\r\n              <ShapeOblongRecognitionNormalization>true</ShapeOblongRecognit" +
            "ionNormalization>\r\n              <IdentifyShapeCertaintyMinimum>65</IdentifyShap" +
            "eCertaintyMinimum>\r\n            </TemplateRecognitionSettings>\r\n          </Imag" +
            "ingSettings>\r\n        ")]
        public global::Galatea.AI.Imaging.ImagingSettings ImagingSettings {
            get {
                return ((global::Galatea.AI.Imaging.ImagingSettings)(this["ImagingSettings"]));
            }
            set {
                this["ImagingSettings"] = value;
            }
        }
    }
}
