//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatea.Speech.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatea.Speech.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Text-To-Speech Interface was successfully Initialized..
        /// </summary>
        internal static string TTS_Initialized {
            get {
                return ResourceManager.GetString("TTS_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech TTS Starting..
        /// </summary>
        internal static string TTS_On_Begin_Speaking {
            get {
                return ResourceManager.GetString("TTS_On_Begin_Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech TTS Paused..
        /// </summary>
        internal static string TTS_On_Paused {
            get {
                return ResourceManager.GetString("TTS_On_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech TTS Resumed..
        /// </summary>
        internal static string TTS_On_Resumed {
            get {
                return ResourceManager.GetString("TTS_On_Resumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speech Text is empty..
        /// </summary>
        internal static string TTS_Speech_Text_Is_Empty {
            get {
                return ResourceManager.GetString("TTS_Speech_Text_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech TTS Stopping..
        /// </summary>
        internal static string TTS_Stopping {
            get {
                return ResourceManager.GetString("TTS_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Phoneme - ph:{0}, eph:{1}, mh:{2}, mw:{3}, mu:{4}, jaw:{5}, upper:{6}, lower:{7}, tongue:{8}, lip:{9}.
        /// </summary>
        internal static string TTS4_On_Visual_Log_Format {
            get {
                return ResourceManager.GetString("TTS4_On_Visual_Log_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech TTS Mouth Position: {0}.
        /// </summary>
        internal static string TTS5_On_MouthPositionChange_Log_Format {
            get {
                return ResourceManager.GetString("TTS5_On_MouthPositionChange_Log_Format", resourceCulture);
            }
        }
    }
}
