//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.Chatbots.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Library\\ChatBots\\AIMLBot\\ConfigurationFiles")]
        public string ChatbotAliceConfigFolder {
            get {
                return ((string)(this["ChatbotAliceConfigFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Resources\\Chatbot")]
        public string ChatbotResourcesFolder {
            get {
                return ((string)(this["ChatbotResourcesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(">{0}: {1}")]
        public string ChatbotMessageFormat {
            get {
                return ((string)(this["ChatbotMessageFormat"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public short ChatbotDisplayResponseWaitTime {
            get {
                return ((short)(this["ChatbotDisplayResponseWaitTime"]));
            }
            set {
                this["ChatbotDisplayResponseWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string ChatbotDefaultName {
            get {
                return ((string)(this["ChatbotDefaultName"]));
            }
            set {
                this["ChatbotDefaultName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I\'m sorry - Do I know you?")]
        public string ChatbotDefaultResponse {
            get {
                return ((string)(this["ChatbotDefaultResponse"]));
            }
            set {
                this["ChatbotDefaultResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Greetings, human!")]
        public string ChatBotAliceGreeting {
            get {
                return ((string)(this["ChatBotAliceGreeting"]));
            }
            set {
                this["ChatBotAliceGreeting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tell me how you are feeling.  I am ready to listen.")]
        public string ChatBotElizaGreeting {
            get {
                return ((string)(this["ChatBotElizaGreeting"]));
            }
            set {
                this["ChatBotElizaGreeting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chatbot Alice Config folder \'{0}\' not found.")]
        public string ChatbotAliceConfigFolder_Not_Found {
            get {
                return ((string)(this["ChatbotAliceConfigFolder_Not_Found"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chatbot Resources folder \'{0}\' not found.")]
        public string ChatbotResourcesFolder_Not_Found {
            get {
                return ((string)(this["ChatbotResourcesFolder_Not_Found"]));
            }
        }
    }
}
