//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gala.Dolly.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string BaseForm_ExitMenuItem_Text {
            get {
                return ResourceManager.GetString("BaseForm_ExitMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string BaseForm_FileMenu_Text {
            get {
                return ResourceManager.GetString("BaseForm_FileMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string BaseForm_toolsMenu_Text {
            get {
                return ResourceManager.GetString("BaseForm_toolsMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string BaseForm_viewMenu_Text {
            get {
                return ResourceManager.GetString("BaseForm_viewMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;{0}: {1}.
        /// </summary>
        internal static string Chatbot_Message_Format {
            get {
                return ResourceManager.GetString("Chatbot_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ChatbotControl_btnSend_Text {
            get {
                return ResourceManager.GetString("ChatbotControl_btnSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHATBOT:.
        /// </summary>
        internal static string ChatbotControl_lblChatBotSelector_Text {
            get {
                return ResourceManager.GetString("ChatbotControl_lblChatBotSelector_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string ChatbotControl_radDefault_Text {
            get {
                return ResourceManager.GetString("ChatbotControl_radDefault_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Dolly {
            get {
                object obj = ResourceManager.GetObject("Dolly", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not initialized properly..
        /// </summary>
        internal static string Startup_Fail_Message_Format {
            get {
                return ResourceManager.GetString("Startup_Fail_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Diagnostic.
        /// </summary>
        internal static string UIDebugger_debugDiagnosticMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugDiagnosticMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Events.
        /// </summary>
        internal static string UIDebugger_debugEventMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugEventMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Log.
        /// </summary>
        internal static string UIDebugger_debugLogMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugLogMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        internal static string UIDebugger_debugMenu_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string UIDebugger_debugMenu_ToolTipText {
            get {
                return ResourceManager.GetString("UIDebugger_debugMenu_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Messages.
        /// </summary>
        internal static string UIDebugger_debugMsgMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugMsgMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Alerts.
        /// </summary>
        internal static string UIDebugger_debugShowAlertsMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_debugShowAlertsMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Speech.
        /// </summary>
        internal static string UIDebugger_speechMenu_Text {
            get {
                return ResourceManager.GetString("UIDebugger_speechMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Silent.
        /// </summary>
        internal static string UIDebugger_speechSilentMenuItem_Text {
            get {
                return ResourceManager.GetString("UIDebugger_speechSilentMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip.
        /// </summary>
        internal static string UIDebugger_toolStrip_Text {
            get {
                return ResourceManager.GetString("UIDebugger_toolStrip_Text", resourceCulture);
            }
        }
    }
}
