//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gala.Dolly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b_eyecam {
            get {
                object obj = ResourceManager.GetObject("b_eyecam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eyecam {
            get {
                object obj = ResourceManager.GetObject("eyecam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_led {
            get {
                object obj = ResourceManager.GetObject("green_led", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lettuce_holder {
            get {
                object obj = ResourceManager.GetObject("lettuce_holder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mic_off {
            get {
                object obj = ResourceManager.GetObject("mic_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mic_on {
            get {
                object obj = ResourceManager.GetObject("mic_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.jpg, *.bmp, *.png)|*.jpg; *.bmp; *.png|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialogImageFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_led {
            get {
                object obj = ResourceManager.GetObject("red_led", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Port.
        /// </summary>
        internal static string SerialInterface_btnClosePort_Text {
            get {
                return ResourceManager.GetString("SerialInterface_btnClosePort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Port.
        /// </summary>
        internal static string SerialInterface_btnOpenPort_Text {
            get {
                return ResourceManager.GetString("SerialInterface_btnOpenPort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SerialInterface_btnSend_Text {
            get {
                return ResourceManager.GetString("SerialInterface_btnSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string SerialInterface_lblCommand_Text {
            get {
                return ResourceManager.GetString("SerialInterface_lblCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string SerialInterface_lblInterval_Text {
            get {
                return ResourceManager.GetString("SerialInterface_lblInterval_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close Port.
        /// </summary>
        internal static string SerialInterface_serialClosePortMenuItem_Text {
            get {
                return ResourceManager.GetString("SerialInterface_serialClosePortMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Log Warnings.
        /// </summary>
        internal static string SerialInterface_serialDisableWarnings_Text {
            get {
                return ResourceManager.GetString("SerialInterface_serialDisableWarnings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&amp;pen at Startup.
        /// </summary>
        internal static string SerialInterface_serialOpenAtStartupMenuItem_Text {
            get {
                return ResourceManager.GetString("SerialInterface_serialOpenAtStartupMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Port.
        /// </summary>
        internal static string SerialInterface_serialOpenPortMenuItem_Text {
            get {
                return ResourceManager.GetString("SerialInterface_serialOpenPortMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Serial Interface.
        /// </summary>
        internal static string SerialInterface_serialToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("SerialInterface_serialToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Serial Interface.
        /// </summary>
        internal static string SerialInterface_viewSerialInterfaceMenuItem_Text {
            get {
                return ResourceManager.GetString("SerialInterface_viewSerialInterfaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between {0} and {1}..
        /// </summary>
        internal static string SerialPortInvalidInterval {
            get {
                return ResourceManager.GetString("SerialPortInvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Serial Port is loading..
        /// </summary>
        internal static string SerialPortLoading {
            get {
                return ResourceManager.GetString("SerialPortLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Serial Port and Baud Rate..
        /// </summary>
        internal static string SerialPortSelectPrompt {
            get {
                return ResourceManager.GetString("SerialPortSelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition: Initializing SAPI recognition context object....
        /// </summary>
        internal static string SpeechRecognitionInitializing {
            get {
                return ResourceManager.GetString("SpeechRecognitionInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition is not running..
        /// </summary>
        internal static string SpeechRecognitionNotLoaded {
            get {
                return ResourceManager.GetString("SpeechRecognitionNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition is pausing..
        /// </summary>
        internal static string SpeechRecognitionPausing {
            get {
                return ResourceManager.GetString("SpeechRecognitionPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition is resuming..
        /// </summary>
        internal static string SpeechRecognitionResuming {
            get {
                return ResourceManager.GetString("SpeechRecognitionResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition: SAPI recognition is stopped..
        /// </summary>
        internal static string SpeechRecognitionStopped {
            get {
                return ResourceManager.GetString("SpeechRecognitionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blobify.
        /// </summary>
        internal static string TemplateRecognition_btnBlobify_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_btnBlobify_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string TemplateRecognition_btnLoad_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_btnLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string TemplateRecognition_btnRandom_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_btnRandom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string TemplateRecognition_lbl_B_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_B_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string TemplateRecognition_lbl_G_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_G_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string TemplateRecognition_lbl_H_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_H_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string TemplateRecognition_lbl_L_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_L_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string TemplateRecognition_lbl_R_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string TemplateRecognition_lbl_S_Text {
            get {
                return ResourceManager.GetString("TemplateRecognition_lbl_S_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TTS_btn1_Text {
            get {
                return ResourceManager.GetString("TTS_btn1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TTS_btn2_Text {
            get {
                return ResourceManager.GetString("TTS_btn2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string TTS_btn4_Text {
            get {
                return ResourceManager.GetString("TTS_btn4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string TTS_btn5_Text {
            get {
                return ResourceManager.GetString("TTS_btn5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string TTS_lblSpeed_Text {
            get {
                return ResourceManager.GetString("TTS_lblSpeed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string TTS_lblVolume_Text {
            get {
                return ResourceManager.GetString("TTS_lblVolume_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ PAGE UP ] - Capture Mouse.
        /// </summary>
        internal static string VisionCapture_btnCapture_Text {
            get {
                return ResourceManager.GetString("VisionCapture_btnCapture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image File.
        /// </summary>
        internal static string VisionCapture_btnLoad_Text {
            get {
                return ResourceManager.GetString("VisionCapture_btnLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ HOME ] - Center.
        /// </summary>
        internal static string VisionCapture_btnPOV_Text {
            get {
                return ResourceManager.GetString("VisionCapture_btnPOV_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ PAGE DN ] - Release Mouse.
        /// </summary>
        internal static string VisionCapture_btnRelease_Text {
            get {
                return ResourceManager.GetString("VisionCapture_btnRelease_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ INSERT ] - Reset Camera.
        /// </summary>
        internal static string VisionCapture_btnResetCamera_Text {
            get {
                return ResourceManager.GetString("VisionCapture_btnResetCamera_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Y- Axis.
        /// </summary>
        internal static string VisionCapture_cbReverseY_Text {
            get {
                return ResourceManager.GetString("VisionCapture_cbReverseY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string VisionCapture_lblDisplaySize_Text {
            get {
                return ResourceManager.GetString("VisionCapture_lblDisplaySize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits.
        /// </summary>
        internal static string VisionCapture_lblLimits_Text {
            get {
                return ResourceManager.GetString("VisionCapture_lblLimits_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string VisionCapture_lblMousePosition_Text {
            get {
                return ResourceManager.GetString("VisionCapture_lblMousePosition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string VisionCapture_lblPan_Text {
            get {
                return ResourceManager.GetString("VisionCapture_lblPan_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt.
        /// </summary>
        internal static string VisionCapture_lblTilt_Text {
            get {
                return ResourceManager.GetString("VisionCapture_lblTilt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string VisionCapture_ui_Text {
            get {
                return ResourceManager.GetString("VisionCapture_ui_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 0 and 150..
        /// </summary>
        internal static string VisionCaptureMinMaxInvalid {
            get {
                return ResourceManager.GetString("VisionCaptureMinMaxInvalid", resourceCulture);
            }
        }
    }
}
