//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MARIA")]
        public string ChatbotName {
            get {
                return ((string)(this["ChatbotName"]));
            }
            set {
                this["ChatbotName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpeechIsSilent {
            get {
                return ((bool)(this["SpeechIsSilent"]));
            }
            set {
                this["SpeechIsSilent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string SuppressAlice {
            get {
                return ((string)(this["SuppressAlice"]));
            }
            set {
                this["SuppressAlice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string SuppressEliza {
            get {
                return ((string)(this["SuppressEliza"]));
            }
            set {
                this["SuppressEliza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peanut")]
        public string DefaultUserName {
            get {
                return ((string)(this["DefaultUserName"]));
            }
            set {
                this["DefaultUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public int TtsRate {
            get {
                return ((int)(this["TtsRate"]));
            }
            set {
                this["TtsRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int TtsVolume {
            get {
                return ((int)(this["TtsVolume"]));
            }
            set {
                this["TtsVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SerialOpenPortAtStartup {
            get {
                return ((bool)(this["SerialOpenPortAtStartup"]));
            }
            set {
                this["SerialOpenPortAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowShowSerialInterface {
            get {
                return ((bool)(this["WindowShowSerialInterface"]));
            }
            set {
                this["WindowShowSerialInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SerialPortDefaultDevice {
            get {
                return ((string)(this["SerialPortDefaultDevice"]));
            }
            set {
                this["SerialPortDefaultDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialPortDefaultBaudRate {
            get {
                return ((int)(this["SerialPortDefaultBaudRate"]));
            }
            set {
                this["SerialPortDefaultBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>I,eye</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ChatbotSubstitutions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChatbotSubstitutions"]));
            }
            set {
                this["ChatbotSubstitutions"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SerialPortIntervalMin {
            get {
                return ((int)(this["SerialPortIntervalMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int SerialPortIntervalMax {
            get {
                return ((int)(this["SerialPortIntervalMax"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SerialPortDefaultInterval {
            get {
                return ((int)(this["SerialPortDefaultInterval"]));
            }
            set {
                this["SerialPortDefaultInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\Log.txt")]
        public string LogFileName {
            get {
                return ((string)(this["LogFileName"]));
            }
            set {
                this["LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string VisionCapturePanMin {
            get {
                return ((string)(this["VisionCapturePanMin"]));
            }
            set {
                this["VisionCapturePanMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string VisionCapturePanMax {
            get {
                return ((string)(this["VisionCapturePanMax"]));
            }
            set {
                this["VisionCapturePanMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public string VisionCaptureTiltMin {
            get {
                return ((string)(this["VisionCaptureTiltMin"]));
            }
            set {
                this["VisionCaptureTiltMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105")]
        public string VisionCaptureTiltMax {
            get {
                return ((string)(this["VisionCaptureTiltMax"]));
            }
            set {
                this["VisionCaptureTiltMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SpeechRecogResumeMicInterval {
            get {
                return ((int)(this["SpeechRecogResumeMicInterval"]));
            }
            set {
                this["SpeechRecogResumeMicInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LanguageModeChatbotOnly {
            get {
                return ((bool)(this["LanguageModeChatbotOnly"]));
            }
            set {
                this["LanguageModeChatbotOnly"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Resources\\SRChatbot.xml")]
        public string SpeechRecogChatbotGrammarRuleFile {
            get {
                return ((string)(this["SpeechRecogChatbotGrammarRuleFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Resources\\SREvaluate.xml")]
        public string SpeechRecogEvaluateGrammarRuleFile {
            get {
                return ((string)(this["SpeechRecogEvaluateGrammarRuleFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SpeechRecogChatbotGrammarRuleID {
            get {
                return ((int)(this["SpeechRecogChatbotGrammarRuleID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string SpeechRecogEvaluateGrammarRuleID {
            get {
                return ((string)(this["SpeechRecogEvaluateGrammarRuleID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Galatea.AI.Imaging.ImagingSettings ImagingSettings {
            get {
                return ((global::Galatea.AI.Imaging.ImagingSettings)(this["ImagingSettings"]));
            }
            set {
                this["ImagingSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Resources\\Test Cases\\Live")]
        public string RecognitionImageSaveFolder {
            get {
                return ((string)(this["RecognitionImageSaveFolder"]));
            }
            set {
                this["RecognitionImageSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecognitionImageSaveImages {
            get {
                return ((bool)(this["RecognitionImageSaveImages"]));
            }
            set {
                this["RecognitionImageSaveImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SerialPortDisableWarning {
            get {
                return ((bool)(this["SerialPortDisableWarning"]));
            }
            set {
                this["SerialPortDisableWarning"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Data\\SerializedData.dat")]
        public string DataAccessManagerConnectionString {
            get {
                return ((string)(this["DataAccessManagerConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TextToSpeechDefaultVoiceIndex {
            get {
                return ((int)(this["TextToSpeechDefaultVoiceIndex"]));
            }
            set {
                this["TextToSpeechDefaultVoiceIndex"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Data\\SerializedFeedbackData.dat")]
        public string FeedbackManagerConnectionString {
            get {
                return ((string)(this["FeedbackManagerConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Local Settings\\app.config")]
        public string LocalSettingsPath {
            get {
                return ((string)(this["LocalSettingsPath"]));
            }
            set {
                this["LocalSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public short ColorTemplateHybridResultThreshold {
            get {
                return ((short)(this["ColorTemplateHybridResultThreshold"]));
            }
            set {
                this["ColorTemplateHybridResultThreshold"] = value;
            }
        }
    }
}
